### ISSUE TITLE
REAME.md links to a phishing page

### ISSUE THREAD

**Issue by ashelleyPurdue** [fossephate/JoyCon-Driver#156]
The sourceforge link in README.md currently leads to a phishing page:
![image](https://user-images.githubusercontent.com/8558767/121268941-e7828780-c88c-11eb-99eb-cda5d8e9f19f.png)

Changing the "http" to "https" results in the connection being refused, leading me to suspect that there's some kind of man-in-the-middle attack going on.

**Comment by hedgehog125** [comment]
Yeah, that happens for me too. Weirdly http://vjoystick.sourceforge.net/joomla/ seems fairly normal, although I wouldn't trust any files there. It might be a hack rather than a man in the middle attack though because the error means it doesn't accept HTTPS requests rather than the certificate being invalid?

**Comment by FLAMINGGAMEZ1** [comment]
That's not really a phishing page. Its not asking you to put in any of your own details which leads me believe that the login is just for the people who are going to fix the website from whatever 'virus' they are talking about.

unless their domain expired and someone else bought it I'm pretty sure that link is for the real vJoy download. Here is a virus total link for the download anyway:
https://www.virustotal.com/gui/file/f103ced4e7ff7ccb49c8415a542c56768ed4da4fea252b8f4ffdac343074654a/detection
