### ISSUE TITLE
The driver doesnt seem to work with my Windows 7 sp1 pc ( Platform update installed)

### ISSUE THREAD

**Issue by BoomBox-8** [fossephate/JoyCon-Driver#73]
**Hey, mfosse , I know I'm late,but your driver doesn't seem t work with my win 7 pc. I downloaded it,but it states that msvcp140.dll is missing,even though the bloody .dll is on my pc. I've downloaded visual c++ numerous times,and triple checked to see if the msvcp140.dll file was there,which it was,but your program isnt detetcting it**

**Comment by CTCaer** [comment]
Depends what you installed.

There are 2 msvcp140.dlls. One for 32bit (x86) and one for 64bit.

Best case for you is to download/install both versions from here:
https://www.microsoft.com/en-us/download/details.aspx?id=48145
If it asks you for repair, because one package is already installed, do it, just in case.
After both of them are installed, restart (for redundancy).

So it doesn't matter if the dll is there. The version and bitness flavor matters.


On another note, the only problem is when you need the msvcp140**d**.dll. This is the debug version and can only be installed by installing visual studio 2015 or 2017

**Comment by Hank-Ryan** [comment]
CTCaer,i have tried but does not work
